"""Generate a shapefile of warnings generated by workshop folks"""
from __future__ import print_function
from geopandas import read_postgis
from pyiem.util import utc, get_dbconn


def read_example():
    """An example"""
    import geopandas as gpd
    df = gpd.read_file('workshop2018.shp')
    print(df['team'].unique())

def main():
    """Go!"""
    sts = utc(2018, 3, 22, 19)
    ets = utc(2018, 3, 22, 20, 30)
    pgconn = get_dbconn('nwa')
    df = read_postgis("""
        SELECT
        to_char(issue at time zone 'UTC',
                'YYYY-MM-DDThh24:MI:SSZ') as utc_issue,
        to_char(expire at time zone 'UTC',
                'YYYY-MM-DDThh24:MI:SSZ') as utc_expire, geom,
        case when emergency then 'T' else 'F' end as emergency, team
        from nwa_warnings
        WHERE issue >= %s and issue < %s
    """, pgconn, params=(sts, ets), geom_col='geom')
    df.to_file('workshop%s.shp' % (sts.year, ))


if __name__ == '__main__':
    # main()
    read_example()
