"""Generate a shapefile of warnings generated by workshop folks

A helpful data point here is to know the exact periods of the workshops!

    2018-03-22 19:00 - 20:30
    2017-03-30 18:40 - 20:30
    2016-03-31 18:10 - 19:50
    2015-03-26 18:40 - 20:10
    2014-03-27 18:40 - 20:10
    2013-04-04 19:10 - 20:40
    2012-03-29 19:10 - 20:40

"""
from __future__ import print_function
import sys

from geopandas import read_postgis
from pyiem.util import utc, get_dbconn


def read_example():
    """An example"""
    import geopandas as gpd
    df = gpd.read_file('workshop2018.shp')
    print(df['team'].unique())


def main(argv):
    """Go!"""
    sts = utc(int(argv[1]), int(argv[2]), int(argv[3]),
              int(argv[4]), int(argv[5]))
    ets = utc(int(argv[1]), int(argv[2]), int(argv[3]),
              int(argv[6]), int(argv[7]))
    pgconn = get_dbconn('nwa')
    df = read_postgis("""
        SELECT
        to_char(issue at time zone 'UTC',
                'YYYY-MM-DDThh24:MI:SSZ') as utc_issue,
        to_char(expire at time zone 'UTC',
                'YYYY-MM-DDThh24:MI:SSZ') as utc_expire, geom,
        case when emergency then 'T' else 'F' end as emergency, team
        from nwa_warnings
        WHERE issue >= %s and issue < %s
    """, pgconn, params=(sts, ets), geom_col='geom')
    df.to_file('workshop%s.shp' % (sts.year, ))
    print("Wrote %s records to shapefile" % (len(df.index), ))


if __name__ == '__main__':
    main(sys.argv)
    # read_example()
